/* soapV3BindingProxy.h
   Generated by gSOAP 2.8.17r from interface.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapV3BindingProxy_H
#define soapV3BindingProxy_H
#include "soapH.h"

class SOAP_CMAC V3BindingProxy : public soap
{ public:
	/// Endpoint URL of service 'V3BindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	V3BindingProxy();
	/// Construct from another engine state
	V3BindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	V3BindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	V3BindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	V3BindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	V3BindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~V3BindingProxy();
	/// Initializer used by constructors
	virtual	void V3BindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'saveUser' (returns error code or SOAP_OK)
	virtual	int saveUser(std::string accesscode, std::string internnumber, std::string username, std::string passwd1, std::string passwd2, std::string passwd3, std::string name, std::string surname, std::string extranames, std::string initials, std::string sex, std::string birthday, std::string birthplace, std::string birthcountry, std::string address, std::string postalcode, std::string location, std::string country, std::string email, std::string mobilephone, std::string homephone, std::string fax, std::string prn, std::string stamboeknummer, std::string basisrol, std::string untis, struct soap_dom_element &return_) { return this->saveUser(NULL, NULL, accesscode, internnumber, username, passwd1, passwd2, passwd3, name, surname, extranames, initials, sex, birthday, birthplace, birthcountry, address, postalcode, location, country, email, mobilephone, homephone, fax, prn, stamboeknummer, basisrol, untis, return_); }
	virtual	int saveUser(const char *endpoint, const char *soap_action, std::string accesscode, std::string internnumber, std::string username, std::string passwd1, std::string passwd2, std::string passwd3, std::string name, std::string surname, std::string extranames, std::string initials, std::string sex, std::string birthday, std::string birthplace, std::string birthcountry, std::string address, std::string postalcode, std::string location, std::string country, std::string email, std::string mobilephone, std::string homephone, std::string fax, std::string prn, std::string stamboeknummer, std::string basisrol, std::string untis, struct soap_dom_element &return_);

	/// Web service operation 'saveClass' (returns error code or SOAP_OK)
	virtual	int saveClass(std::string accesscode, std::string name, std::string desc, std::string code, std::string parent, std::string untis, std::string instituteNumber, std::string adminNumber, std::string schoolYearDate, struct soap_dom_element &return_) { return this->saveClass(NULL, NULL, accesscode, name, desc, code, parent, untis, instituteNumber, adminNumber, schoolYearDate, return_); }
	virtual	int saveClass(const char *endpoint, const char *soap_action, std::string accesscode, std::string name, std::string desc, std::string code, std::string parent, std::string untis, std::string instituteNumber, std::string adminNumber, std::string schoolYearDate, struct soap_dom_element &return_);

	/// Web service operation 'saveGroup' (returns error code or SOAP_OK)
	virtual	int saveGroup(std::string accesscode, std::string name, std::string desc, std::string code, std::string parent, std::string untis, struct soap_dom_element &return_) { return this->saveGroup(NULL, NULL, accesscode, name, desc, code, parent, untis, return_); }
	virtual	int saveGroup(const char *endpoint, const char *soap_action, std::string accesscode, std::string name, std::string desc, std::string code, std::string parent, std::string untis, struct soap_dom_element &return_);

	/// Web service operation 'getAllAccounts' (returns error code or SOAP_OK)
	virtual	int getAllAccounts(std::string accesscode, std::string code, std::string recursive, struct soap_dom_element &return_) { return this->getAllAccounts(NULL, NULL, accesscode, code, recursive, return_); }
	virtual	int getAllAccounts(const char *endpoint, const char *soap_action, std::string accesscode, std::string code, std::string recursive, struct soap_dom_element &return_);

	/// Web service operation 'getAllAccountsExtended' (returns error code or SOAP_OK)
	virtual	int getAllAccountsExtended(std::string accesscode, std::string code, std::string recursive, struct soap_dom_element &return_) { return this->getAllAccountsExtended(NULL, NULL, accesscode, code, recursive, return_); }
	virtual	int getAllAccountsExtended(const char *endpoint, const char *soap_action, std::string accesscode, std::string code, std::string recursive, struct soap_dom_element &return_);

	/// Web service operation 'getAllGroupsAndClasses' (returns error code or SOAP_OK)
	virtual	int getAllGroupsAndClasses(std::string accesscode, struct soap_dom_element &return_) { return this->getAllGroupsAndClasses(NULL, NULL, accesscode, return_); }
	virtual	int getAllGroupsAndClasses(const char *endpoint, const char *soap_action, std::string accesscode, struct soap_dom_element &return_);

	/// Web service operation 'addCourse' (returns error code or SOAP_OK)
	virtual	int addCourse(std::string accesscode, std::string coursename, std::string coursedesc, std::string &return_) { return this->addCourse(NULL, NULL, accesscode, coursename, coursedesc, return_); }
	virtual	int addCourse(const char *endpoint, const char *soap_action, std::string accesscode, std::string coursename, std::string coursedesc, std::string &return_);

	/// Web service operation 'addCourseTeacher' (returns error code or SOAP_OK)
	virtual	int addCourseTeacher(std::string accesscode, std::string coursename, std::string coursedesc, std::string internnummer, std::string userlist, struct soap_dom_element &return_) { return this->addCourseTeacher(NULL, NULL, accesscode, coursename, coursedesc, internnummer, userlist, return_); }
	virtual	int addCourseTeacher(const char *endpoint, const char *soap_action, std::string accesscode, std::string coursename, std::string coursedesc, std::string internnummer, std::string userlist, struct soap_dom_element &return_);

	/// Web service operation 'addCourseStudents' (returns error code or SOAP_OK)
	virtual	int addCourseStudents(std::string accesscode, std::string coursename, std::string coursedesc, std::string groupIds, struct soap_dom_element &return_) { return this->addCourseStudents(NULL, NULL, accesscode, coursename, coursedesc, groupIds, return_); }
	virtual	int addCourseStudents(const char *endpoint, const char *soap_action, std::string accesscode, std::string coursename, std::string coursedesc, std::string groupIds, struct soap_dom_element &return_);

	/// Web service operation 'getCourses' (returns error code or SOAP_OK)
	virtual	int getCourses(std::string accesscode, std::string &return_) { return this->getCourses(NULL, NULL, accesscode, return_); }
	virtual	int getCourses(const char *endpoint, const char *soap_action, std::string accesscode, std::string &return_);

	/// Web service operation 'delUser' (returns error code or SOAP_OK)
	virtual	int delUser(std::string accesscode, std::string userIdentifier, std::string officialDate, struct soap_dom_element &return_) { return this->delUser(NULL, NULL, accesscode, userIdentifier, officialDate, return_); }
	virtual	int delUser(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string officialDate, struct soap_dom_element &return_);

	/// Web service operation 'saveUserParameter' (returns error code or SOAP_OK)
	virtual	int saveUserParameter(std::string accesscode, std::string userIdentifier, std::string paramName, std::string paramValue, struct soap_dom_element &return_) { return this->saveUserParameter(NULL, NULL, accesscode, userIdentifier, paramName, paramValue, return_); }
	virtual	int saveUserParameter(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string paramName, std::string paramValue, struct soap_dom_element &return_);

	/// Web service operation 'getClassList' (returns error code or SOAP_OK)
	virtual	int getClassList(struct soap_dom_element accesscode, std::string &return_) { return this->getClassList(NULL, NULL, accesscode, return_); }
	virtual	int getClassList(const char *endpoint, const char *soap_action, struct soap_dom_element accesscode, std::string &return_);

	/// Web service operation 'getClassListJson' (returns error code or SOAP_OK)
	virtual	int getClassListJson(struct soap_dom_element accesscode, std::string &return_) { return this->getClassListJson(NULL, NULL, accesscode, return_); }
	virtual	int getClassListJson(const char *endpoint, const char *soap_action, struct soap_dom_element accesscode, std::string &return_);

	/// Web service operation 'saveClassList' (returns error code or SOAP_OK)
	virtual	int saveClassList(std::string accesscode, std::string serializedList, struct soap_dom_element &return_) { return this->saveClassList(NULL, NULL, accesscode, serializedList, return_); }
	virtual	int saveClassList(const char *endpoint, const char *soap_action, std::string accesscode, std::string serializedList, struct soap_dom_element &return_);

	/// Web service operation 'saveClassListJson' (returns error code or SOAP_OK)
	virtual	int saveClassListJson(std::string accesscode, std::string jsonList, struct soap_dom_element &return_) { return this->saveClassListJson(NULL, NULL, accesscode, jsonList, return_); }
	virtual	int saveClassListJson(const char *endpoint, const char *soap_action, std::string accesscode, std::string jsonList, struct soap_dom_element &return_);

	/// Web service operation 'delClass' (returns error code or SOAP_OK)
	virtual	int delClass(std::string accesscode, std::string code, struct soap_dom_element &return_) { return this->delClass(NULL, NULL, accesscode, code, return_); }
	virtual	int delClass(const char *endpoint, const char *soap_action, std::string accesscode, std::string code, struct soap_dom_element &return_);

	/// Web service operation 'saveUserToClasses' (returns error code or SOAP_OK)
	virtual	int saveUserToClasses(std::string accesscode, std::string userIdentifier, std::string csvList, struct soap_dom_element &return_) { return this->saveUserToClasses(NULL, NULL, accesscode, userIdentifier, csvList, return_); }
	virtual	int saveUserToClasses(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string csvList, struct soap_dom_element &return_);

	/// Web service operation 'removeUserFromGroup' (returns error code or SOAP_OK)
	virtual	int removeUserFromGroup(std::string accesscode, std::string userIdentifier, std::string class_, std::string officialDate, struct soap_dom_element &return_) { return this->removeUserFromGroup(NULL, NULL, accesscode, userIdentifier, class_, officialDate, return_); }
	virtual	int removeUserFromGroup(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string class_, std::string officialDate, struct soap_dom_element &return_);

	/// Web service operation 'saveUserToClass' (returns error code or SOAP_OK)
	virtual	int saveUserToClass(std::string accesscode, std::string userIdentifier, std::string class_, std::string officialDate, struct soap_dom_element &return_) { return this->saveUserToClass(NULL, NULL, accesscode, userIdentifier, class_, officialDate, return_); }
	virtual	int saveUserToClass(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string class_, std::string officialDate, struct soap_dom_element &return_);

	/// Web service operation 'saveUserToClassesAndGroups' (returns error code or SOAP_OK)
	virtual	int saveUserToClassesAndGroups(std::string accesscode, std::string userIdentifier, std::string csvList, int keepOld, struct soap_dom_element &return_) { return this->saveUserToClassesAndGroups(NULL, NULL, accesscode, userIdentifier, csvList, keepOld, return_); }
	virtual	int saveUserToClassesAndGroups(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string csvList, int keepOld, struct soap_dom_element &return_);

	/// Web service operation 'setAccountStatus' (returns error code or SOAP_OK)
	virtual	int setAccountStatus(std::string accesscode, std::string userIdentifier, struct soap_dom_element accountStatus, struct soap_dom_element &return_) { return this->setAccountStatus(NULL, NULL, accesscode, userIdentifier, accountStatus, return_); }
	virtual	int setAccountStatus(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, struct soap_dom_element accountStatus, struct soap_dom_element &return_);

	/// Web service operation 'setAccountPhoto' (returns error code or SOAP_OK)
	virtual	int setAccountPhoto(std::string accesscode, std::string userIdentifier, std::string photo, struct soap_dom_element &return_) { return this->setAccountPhoto(NULL, NULL, accesscode, userIdentifier, photo, return_); }
	virtual	int setAccountPhoto(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string photo, struct soap_dom_element &return_);

	/// Web service operation 'getAccountPhoto' (returns error code or SOAP_OK)
	virtual	int getAccountPhoto(std::string accesscode, std::string userIdentifier, std::string &return_) { return this->getAccountPhoto(NULL, NULL, accesscode, userIdentifier, return_); }
	virtual	int getAccountPhoto(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string &return_);

	/// Web service operation 'replaceInum' (returns error code or SOAP_OK)
	virtual	int replaceInum(std::string accesscode, std::string oldInum, std::string newInum, struct soap_dom_element &return_) { return this->replaceInum(NULL, NULL, accesscode, oldInum, newInum, return_); }
	virtual	int replaceInum(const char *endpoint, const char *soap_action, std::string accesscode, std::string oldInum, std::string newInum, struct soap_dom_element &return_);

	/// Web service operation 'forcePasswordReset' (returns error code or SOAP_OK)
	virtual	int forcePasswordReset(std::string accesscode, std::string userIdentifier, int accountType, struct soap_dom_element &return_) { return this->forcePasswordReset(NULL, NULL, accesscode, userIdentifier, accountType, return_); }
	virtual	int forcePasswordReset(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, int accountType, struct soap_dom_element &return_);

	/// Web service operation 'savePassword' (returns error code or SOAP_OK)
	virtual	int savePassword(std::string accesscode, std::string userIdentifier, std::string password, int accountType, struct soap_dom_element &return_) { return this->savePassword(NULL, NULL, accesscode, userIdentifier, password, accountType, return_); }
	virtual	int savePassword(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string password, int accountType, struct soap_dom_element &return_);

	/// Web service operation 'sendMsg' (returns error code or SOAP_OK)
	virtual	int sendMsg(std::string accesscode, std::string userIdentifier, std::string title, std::string body, std::string senderIdentifier, struct soap_dom_element attachments, int coaccount, struct soap_dom_element &return_) { return this->sendMsg(NULL, NULL, accesscode, userIdentifier, title, body, senderIdentifier, attachments, coaccount, return_); }
	virtual	int sendMsg(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string title, std::string body, std::string senderIdentifier, struct soap_dom_element attachments, int coaccount, struct soap_dom_element &return_);

	/// Web service operation 'getSkoreClassTeacherCourseRelation' (returns error code or SOAP_OK)
	virtual	int getSkoreClassTeacherCourseRelation(std::string accesscode, struct soap_dom_element &return_) { return this->getSkoreClassTeacherCourseRelation(NULL, NULL, accesscode, return_); }
	virtual	int getSkoreClassTeacherCourseRelation(const char *endpoint, const char *soap_action, std::string accesscode, struct soap_dom_element &return_);

	/// Web service operation 'unregisterStudent' (returns error code or SOAP_OK)
	virtual	int unregisterStudent(std::string accesscode, std::string userIdentifier, std::string officialDate, struct soap_dom_element &return_) { return this->unregisterStudent(NULL, NULL, accesscode, userIdentifier, officialDate, return_); }
	virtual	int unregisterStudent(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string officialDate, struct soap_dom_element &return_);

	/// Web service operation 'getClassTeachers' (returns error code or SOAP_OK)
	virtual	int getClassTeachers(std::string accesscode, bool getAllOwners, struct soap_dom_element &return_) { return this->getClassTeachers(NULL, NULL, accesscode, getAllOwners, return_); }
	virtual	int getClassTeachers(const char *endpoint, const char *soap_action, std::string accesscode, bool getAllOwners, struct soap_dom_element &return_);

	/// Web service operation 'getAbsentsByDate' (returns error code or SOAP_OK)
	virtual	int getAbsentsByDate(std::string accesscode, std::string date, std::string &return_) { return this->getAbsentsByDate(NULL, NULL, accesscode, date, return_); }
	virtual	int getAbsentsByDate(const char *endpoint, const char *soap_action, std::string accesscode, std::string date, std::string &return_);

	/// Web service operation 'getAbsents' (returns error code or SOAP_OK)
	virtual	int getAbsents(std::string accesscode, std::string userIdentifier, std::string schoolYear, std::string &return_) { return this->getAbsents(NULL, NULL, accesscode, userIdentifier, schoolYear, return_); }
	virtual	int getAbsents(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string schoolYear, std::string &return_);

	/// Web service operation 'getUserDetails' (returns error code or SOAP_OK)
	virtual	int getUserDetails(std::string accesscode, std::string userIdentifier, std::string &return_) { return this->getUserDetails(NULL, NULL, accesscode, userIdentifier, return_); }
	virtual	int getUserDetails(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string &return_);

	/// Web service operation 'getUserDetailsByNumber' (returns error code or SOAP_OK)
	virtual	int getUserDetailsByNumber(std::string accesscode, std::string number, std::string &return_) { return this->getUserDetailsByNumber(NULL, NULL, accesscode, number, return_); }
	virtual	int getUserDetailsByNumber(const char *endpoint, const char *soap_action, std::string accesscode, std::string number, std::string &return_);

	/// Web service operation 'getUserDetailsByUsername' (returns error code or SOAP_OK)
	virtual	int getUserDetailsByUsername(std::string accesscode, std::string username, std::string &return_) { return this->getUserDetailsByUsername(NULL, NULL, accesscode, username, return_); }
	virtual	int getUserDetailsByUsername(const char *endpoint, const char *soap_action, std::string accesscode, std::string username, std::string &return_);

	/// Web service operation 'getUserOfficialClass' (returns error code or SOAP_OK)
	virtual	int getUserOfficialClass(std::string accesscode, std::string userIdentifier, std::string date, std::string &return_) { return this->getUserOfficialClass(NULL, NULL, accesscode, userIdentifier, date, return_); }
	virtual	int getUserOfficialClass(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string date, std::string &return_);

	/// Web service operation 'saveSignature' (returns error code or SOAP_OK)
	virtual	int saveSignature(std::string accesscode, std::string userIdentifier, int accountType, std::string signature, bool &return_) { return this->saveSignature(NULL, NULL, accesscode, userIdentifier, accountType, signature, return_); }
	virtual	int saveSignature(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, int accountType, std::string signature, bool &return_);

	/// Web service operation 'getStudentCareer' (returns error code or SOAP_OK)
	virtual	int getStudentCareer(std::string accesscode, std::string userIdentifier, std::string &return_) { return this->getStudentCareer(NULL, NULL, accesscode, userIdentifier, return_); }
	virtual	int getStudentCareer(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, std::string &return_);

	/// Web service operation 'deactivateTwoFactorAuthentication' (returns error code or SOAP_OK)
	virtual	int deactivateTwoFactorAuthentication(std::string accesscode, std::string userIdentifier, int accountType, struct soap_dom_element &return_) { return this->deactivateTwoFactorAuthentication(NULL, NULL, accesscode, userIdentifier, accountType, return_); }
	virtual	int deactivateTwoFactorAuthentication(const char *endpoint, const char *soap_action, std::string accesscode, std::string userIdentifier, int accountType, struct soap_dom_element &return_);

	/// Web service one-way send operation 'send_returnErrorCodes' (returns error code or SOAP_OK)
	virtual	int send_returnErrorCodes() { return this->send_returnErrorCodes(NULL, NULL); }
	virtual	int send_returnErrorCodes(const char *endpoint, const char *soap_action);
	/// Web service one-way receive operation 'recv_returnErrorCodes' (returns error code or SOAP_OK);
	virtual	int recv_returnErrorCodes(struct ns1__returnErrorCodes&);
	/// Web service receive of HTTP Accept acknowledgment for one-way send operation 'send_returnErrorCodes' (returns error code or SOAP_OK)
	virtual	int recv_returnErrorCodes_empty_response() { return soap_recv_empty_response(this); }
	/// Web service one-way synchronous send operation 'returnErrorCodes' with HTTP Accept/OK response receive (returns error code or SOAP_OK)
	virtual	int returnErrorCodes() { return this->returnErrorCodes(NULL, NULL); }
	virtual	int returnErrorCodes(const char *endpoint, const char *soap_action) { if (this->send_returnErrorCodes(endpoint, soap_action) || soap_recv_empty_response(this)) return this->error; return SOAP_OK; }

	/// Web service operation 'returnCsvErrorCodes' (returns error code or SOAP_OK)
	virtual	int returnCsvErrorCodes(std::string &return_) { return this->returnCsvErrorCodes(NULL, NULL, return_); }
	virtual	int returnCsvErrorCodes(const char *endpoint, const char *soap_action, std::string &return_);

	/// Web service operation 'returnJsonErrorCodes' (returns error code or SOAP_OK)
	virtual	int returnJsonErrorCodes(std::string &return_) { return this->returnJsonErrorCodes(NULL, NULL, return_); }
	virtual	int returnJsonErrorCodes(const char *endpoint, const char *soap_action, std::string &return_);
};
#endif
