#!/bin/bash
. scripts/functions
. scripts/gui
. scripts/verify_cluster
. scripts/install_yatools
. scripts/verify_drbd
. scripts/db_functions

printBox "Welcome to yvan's admin tools!"
installPackage dialog

scripts/mainMenu
clear

