#!/bin/bash
. scripts/functions
. scripts/verify_software
. scripts/install_yatools

printBox "Welcome to yvan's admin tools!"

verifySoftware
installAdminTools
installCockpit
installYearbook


#start cockpit
cockpit
