#!/bin/bash

. scripts/gui

installPackage() {
  problem=$(dpkg -s $1|grep installed)
  
  if [ "" == "$problem" ]; then
    printChange "package $1" "INSTALLING"
    apt-get -y install $1
    problem2=$(dpkg -s $1|grep installed)
    if [ "" == "$problem2" ]; then
       printFailed "package $1" "NOT INSTALLED"
    fi
  else 
    printSuccess "package $1" "INSTALLED"
  fi

}

addCronJob() {
  job="$1 $2"
  cat <(fgrep -i -v "$2" <(crontab -l)) <(echo "$job") | crontab
}

createDir() {
  if [ ! -d $1 ]; then
    mkdir $1
  fi
}

restartService() {
  service $1 restart
  if ps ax | grep -v grep | grep -v $0 | grep $1 > /dev/null
  then 
    printSuccess "Service $1 should be running" "OK"
  else
    printFailed "Service $1 should be running" "NO" 
    read -p "you might want to stop this script and fix this!"
  fi
}

