#!/bin/bash

printSuccess() {
  printf "\E[97m%50s \E[92m%25s \n" "$1" "$2"
  tput sgr0
}

printFailed() {
  printf "\E[97m%50s \E[91m%25s \n" "$1" "$2"
  tput sgr0
}

printChange() {
  printf "\E[97m%50s \E[34m%25s \n" "$1" "$2"
  tput sgr0
}

printBox() {
  str="$1"
  len=$((${#str}+4))
  echo -e "\E[34m"
  for i in $(seq $len); do echo -n '*'; done;
  echo; echo "* "$str" *";
  for i in $(seq $len); do echo -n '*'; done;
  echo
  tput sgr0
}

waitForEnter() {
  read -p "Press [Enter] key to continue..."
}

showMessage() {
  dialog --backtitle "yvan's admin tools" \
         --title "$1" \
         --msgbox "$2" 6 40
}

showQuestion() {
  dialog --backtitle "yvan's admin tools" \
         --title "$1" \
         --yesno "$2" 7 60
}

showInput() {
  DIALOGINPUT=/tmp/dialoginput.sh.$$
  dialog --backtitle "yvan's admin tools" \
         --title "$1" \
         --inputbox "$2" 8 60 2>$DIALOGINPUT
  response=$?
  
  case $response in
    0)  eval $3="$(<$DIALOGINPUT)" 
        ;;
  esac

  rm $DIALOGINPUT
}        
