#!/bin/bash
. scripts/functions


# install cockpit
installCockpit(){
echo
read -r -p "Install cockpit?[y/N]" response
response=${response,,}
if [[ $response =~ (yes|y)$ ]]
then
  git pull
  cd cockpit
  make CONF=Release build
  cp dist/Release/GNU-Linux-x86/cockpit /sbin
  cd ..
  createDir /root/admintools
fi
}

