#!/bin/bash
# Store menu options selected by the user
INPUT=/tmp/menu.sh.$$

. scripts/git_functions
 
# trap and delete temp files
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM

#proper shutdown
exitScript() {
  [ -f $INPUT ] && rm $INPUT
  exit
}
 
#
# set infinite loop
#
while true
do
 
### display main menu ###
dialog --clear --backtitle "yvan's admin tools" \
--title "[ M A I N - M E N U ]" \
--menu "Choose a TASK" 15 60 4 \
Installation "Verifies software installation" \
Identity "View and Modify this system's Identity" \
HA "Control High Availability Server" \
Git "Send updates to Git Repository" \
Exit "Exit to the shell" 2>"${INPUT}"

opt=$?
[[ "$opt" -eq 1 ]] && exitScript
 
menuitem=$(<"${INPUT}")
 
# make decision 
case $menuitem in
	Installation) echo "installation";;
	Identity) echo "identitiy";;
	HA) echo "ha";;
        Git) sendToGit;;
	Exit) break;;
esac

done
 
exitScript
