#!/bin/bash
# Store menu options selected by the user
INPUT=/tmp/menu.sh.$$

. scripts/git_functions
. scripts/verify_software
. scripts/system_config
. scripts/verify_ha
 
# trap and delete temp files
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM

#proper shutdown
exitScript() {
  [ -f $INPUT ] && rm $INPUT
  exit
}
 
#
# set infinite loop
#
while true
do
 
### display main menu ###
dialog --clear --backtitle "yvan's admin tools" \
--title "[ M A I N - M E N U ]" \
--menu "Choose a TASK" 15 60 8 \
Installation "Verifies software installation" \
Configuration "This system's Configuration" \
HA "Control High Availability Server" \
Git "Send updates to Git Repository" \
Exit "Exit to the shell" 2>"${INPUT}"

opt=$?
[[ "$opt" -eq 1 ]] && exitScript
 
menuitem=$(<"${INPUT}")
 
# make decision 
case $menuitem in
	Installation) verifyInstalledSoftware;;
	Configuration) sysConfig;;
	HA) verifyHA;;
        Git) sendToGit;;
	Exit) break;;
esac

done
 
exitScript
